version: "3.4"

volumes:
  arbitrum:

services:
  caff_node:
    image: ghcr.io/espressosystems/nitro-espresso-integration/nitro-node:v3.5.6-celestia-9c5e4c9
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - "${PWD}/nodeConfig.json:/config/nodeConfig.json"
      - arbitrum:/home/user/.arbitrum
    entrypoint:
      - "/usr/local/bin/nitro"
      - --conf.file=/config/nodeConfig.json
      - --parent-chain.connection.url=https://arb1.arbitrum.io/rpc
